<a href="https://colab.research.google.com/github/aadi-29/machinelearning/blob/main/ML_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt

#model specific library

from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
import sklearn.metrics as metrics
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv('breast-cancer-wisconsin.csv')
df=df[df.ne('?').all(1)].astype(int)
df.columns=['id', 'Clump Thickness', 'Cell size', 'cell shape', 'Adhesion', 'Epithelial Cell', 'Bare nuclei', 'Bland Chromatin', 'Normal nucleoli', 'Mitoses', 'Class']
df.shape
data=np.array(df)
X=data[:,:-1]
y=data[:,-1]
X

array([[1002945,       5,       4, ...,       3,       2,       1],
       [1015425,       3,       1, ...,       3,       1,       1],
       [1016277,       6,       8, ...,       3,       7,       1],
       ...,
       [ 888820,       5,      10, ...,       8,      10,       2],
       [ 897471,       4,       8, ...,      10,       6,       1],
       [ 897471,       4,       8, ...,      10,       4,       1]])

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=50)

In [ ]:
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [ ]:
principal = PCA(0.80)
principal.fit(X_train)
x=principal.transform(X_train)
x_test=principal.transform(X_test)

#check the dimesnions of data after PCA
print(x.shape)

(477, 4)


In [ ]:
x

array([[-1.81849459,  1.37067076,  0.03364056, -0.72127372],
       [ 3.14043677, -0.9132151 , -0.59409747,  0.39780788],
       [-1.86739063,  1.47545023,  0.1517633 , -0.68041794],
       ...,
       [ 6.78951987,  1.3775058 ,  3.32196394,  0.52923855],
       [ 2.5410485 , -0.03535219, -0.75155249,  0.97317622],
       [-2.32130837, -0.30918639,  0.23336756, -0.38347399]])

In [ ]:
principal.explained_variance_ratio_

array([0.59256489, 0.1019823 , 0.07505003, 0.0533842 ])

In [ ]:
print(principal.components_)
print(principal.explained_variance_)

[[-0.03875387  0.30636177  0.37951582  0.37560508  0.33553815  0.33478076
   0.33873087  0.3415202   0.32481583  0.24080115]
 [-0.97661133 -0.01931873 -0.10646427 -0.06897308  0.05593432 -0.05091817
   0.11115617 -0.03248177 -0.04862596  0.09093197]
 [ 0.05102178 -0.13737421 -0.03603214 -0.0790584  -0.10757935  0.19171645
  -0.28129432 -0.23437055  0.06596083  0.88557392]
 [ 0.03271187  0.83237115 -0.05476022  0.02140997 -0.27093733 -0.10908543
   0.16245942 -0.27748498 -0.31575213  0.11930671]]
[5.93809778 1.02196553 0.75207697 0.53496354]


In [ ]:
gnb = GaussianNB()
y_pred=gnb.fit(x,y_train).predict(x_test)

In [ ]:
metrics.accuracy_score(y_test,y_pred)*100

93.65853658536587